version: "3"
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
  wordpress:
    depends_on:
      - mysql
    image: wordpress:latest
    deploy:
      replicas: 1
      placement:
        constraints: [node.role==manager]
    environment:
      VIRTUAL_HOST: wp.deweixiang.com
      WORDPRESS_DB_PASSWORD: "mypass_user"
      WORDPRESS_DB_USER: "myuser"
      WORDPRESS_DB_NAME: "wordpressDB1"
      WORDPRESS_DB_HOST: mysql:3306
    links:
      - mysql
    depends_on:
      - mysql
    ports:
      - 80
  mysql:
    image: mysql:5.7
    environment:
      VIRTUAL_HOST: mysql.deweixiang.com
      MYSQL_ROOT_PASSWORD: "root_password"
      MYSQL_DATABASE: "wordpressDB1"
      MYSQL_USER: "myuser"
      MYSQL_PASSWORD: "mypass_user"
    ports:
      - 3306:3306
    deploy:
      placement:
        constraints: [node.role==manager]
  notebook:
    image: jupyter/tensorflow-notebook
    environment:
      VIRTUAL_HOST: notebook.deweixiang.com
    deploy:
      placement:
        constraints: [node.role==node]