version: "3"
services:
  web:
    depends_on:
      - mysql
    # replace username/repo:tag with your name and image details
    image: wordpress:latest
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    environment:
      VIRTUAL_HOST: ondemand.deweixiang.com
      WORDPRESS_DB_PASSWORD: "mypass_user"
      WORDPRESS_DB_USER: "myuser"
      WORDPRESS_DB_NAME: "wordpressDB"
    depends_on:
      - mysql
    ports:
      - 14225:80
    volumes:
      - ./data/wordpress:/var/www/html
    networks:
      - webnet
      - nginx-proxy
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: "root_password"
      MYSQL_DATABASE: "wordpressDB"
      MYSQL_ROOT_HOST: "%"
      MYSQL_USER: "myuser"
      MYSQL_PASSWORD: "mypass_user"
    ports:
      - 3306:3306
    volumes:
      - ./data/mysql:/var/lib/mysql
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - webnet
networks:
  webnet:
  nginx-proxy:
    external:
      name: nginx_proxy_default