version: "3"
services:
  nginx-proxy:
    image: jwilder/nginx-proxy:alpine
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
  notebook:
    image: jupyter/tensorflow-notebook
    environment:
      VIRTUAL_HOST: notebook.deweixiang.com
    ports:
      - "8088:80"
    deploy:
      placement:
        constraints: [node.role == manager]
