version: "3"
services:
  nginx-proxy:
    image: jwilder/nginx-proxy:latest
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - webnet
  wordpress:
    depends_on:
      - mysql
    image: wordpress:latest
    deploy:
      replicas: 1
      placement:
        constraints: []
    environment:
      VIRTUAL_HOST: www.mytvglobal.com,mytvglobal.com
      WORDPRESS_DB_PASSWORD: "mypass_user"
      WORDPRESS_DB_USER: "myuser"
      WORDPRESS_DB_NAME: "wordpressDB1"
      WORDPRESS_DB_HOST: mysql:3306
    depends_on:
      - mysql
    ports:
      - "8081:8080"
    expose:
      - 8081
    networks:
      - webnet
  wordpress2:
    depends_on:
      - mysql
    image: wordpress:latest
    deploy:
      replicas: 1
      placement:
        constraints: []
    environment:
      VIRTUAL_HOST: www.deweixiang.com,deweixiang.com
      WORDPRESS_DB_PASSWORD: "root_password"
      WORDPRESS_DB_USER: "root"
      WORDPRESS_DB_NAME: "wp_dewei"
      WORDPRESS_DB_HOST: mysql:3306
    depends_on:
      - mysql
    ports:
      - "8081:8080"
    expose:
      - 8081
    networks:
      - webnet
      

  mysql:
    image: mysql:5.7
    volumes:
       - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "root_password"
      MYSQL_DATABASE: "wordpressDB1"
      MYSQL_USER: "myuser"
      MYSQL_PASSWORD: "mypass_user"
    ports:
      - 3306:3306
    expose:
      - 3306
    deploy:
      placement:
        constraints: []
    networks:
      - webnet
  
networks:
  webnet:
    driver: overlay
volumes:
    db_data: