version: "3"
services:
  nginx-proxy:
    image: jwilder/nginx-proxy:latest
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - webnet
  wordpress:
    depends_on:
      - mysql
    image: wordpress:latest
    deploy:
      replicas: 1
      placement:
        constraints: []
    environment:
      VIRTUAL_HOST: wp.deweixiang.com,wp.whoami.local
      WORDPRESS_DB_PASSWORD: "mypass_user"
      WORDPRESS_DB_USER: "myuser"
      WORDPRESS_DB_NAME: "wordpressDB1"
      WORDPRESS_DB_HOST: mysql.deweixiang.com:3306
    depends_on:
      - mysql
    ports:
      - "8081:8080"
    expose:
      - 8081
    networks:
      - webnet
  mysql:
    image: mysql:5.7
    volumes:
       - db_data:/var/lib/mysql
    environment:
      VIRTUAL_HOST: mysql.deweixiang.com,mysql.whoami.local
      MYSQL_ROOT_PASSWORD: "root_password"
      MYSQL_DATABASE: "wordpressDB1"
      MYSQL_USER: "myuser"
      MYSQL_PASSWORD: "mypass_user"
    ports:
      - 3306:3306
    expose:
      - 3306
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - webnet
  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8082:8080"
    expose:
      - 8082
    environment:
      VIRTUAL_HOST: status.deweixiang.com,status.whoami.local
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - webnet
  notebook:
    image: jupyter/tensorflow-notebook
    environment:
      VIRTUAL_HOST: notebook.deweixiang.com
    expose:
      - 8083
    ports:
      - "8083:8888"
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - webnet
  web:
    # replace username/repo:tag with your name and image details
    image: microsoft/dotnet-samples:aspnetapp
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
    environment:
      VIRTUAL_HOST: web.deweixiang.com
    expose:
      - 8084
    ports:
      - "8084:8080"
    networks:
      - webnet
networks:
  webnet:
    driver: overlay
volumes:
    db_data: